[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "backend_py"
version = "0.1.0"
description = "Backend for data visualization project"
requires-python = ">=3.11" 